/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package system.views;

import javax.swing.JLabel;
import javax.swing.JSlider;

/**
 *
 * @author 
 */
public class PouringGUI extends javax.swing.JFrame {

    private static PouringGUI instance;
    
    public static PouringGUI getInstance(){
        if(instance != null)
            return instance;
        else
            return instance=new PouringGUI();
    }
    
    /**
     * Creates new form PouringGUI
     */
    private PouringGUI() {
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                setVisible(true);
                setLocation(CoffeeMachineGUI.getCoffeeMachineGUI().getX() + CoffeeMachineGUI.getCoffeeMachineGUI().getWidth(), MachineStatsGUI.getInstance().getY()+MachineStatsGUI.getInstance().getHeight());
            }
        });
        initComponents();
    }

    public JSlider getDrink() {
        return Drink;
    }

    public JLabel getCupSize() {
        return cupSize;
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Drink = new javax.swing.JSlider();
        cupSize = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Drink.setOrientation(javax.swing.JSlider.VERTICAL);
        Drink.setValue(0);
        getContentPane().add(Drink, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 60, 80, 260));
        getContentPane().add(cupSize, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 140, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/system/views/coffee_minimal_wallpapers_by_webmozg-d3d9qfb - Copy.jpg"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(-200, -140, 520, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSlider Drink;
    private javax.swing.JLabel cupSize;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
