/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package system.views;

import Model.Money_Dispenser;
import backend.event.engine.Engine;
import java.awt.Color;
import javax.swing.JTextArea;
import javax.swing.JTextField;
import system.events.*;



/**
 *
 * @author ragrag
 */
public class WaterHeater_VIEW extends javax.swing.JFrame {

    /**
     * Creates new form WaterHeater_VIEW
     */
    private static final WaterHeater_VIEW waterHeaterView = new WaterHeater_VIEW();

    public void setTemp(String tempreture) {
        this.tempreture.setText(tempreture);
    }

    public void setPower(Boolean power) {
        String pow = power ? "ON" : "OFF";
        this.power.setText(pow);
        if (pow == "ON") {
            this.power.setForeground(Color.GREEN);
        } else if (pow == "OFF") {
            this.power.setForeground(Color.RED);
        }
    }

    public void setStatus(String status) {
        this.status.setText(status);
        if (status == "COOLING") {
            this.status.setForeground(Color.BLUE);
        } else if (status == "HEATING") {
            this.status.setForeground(Color.RED);
        } else {
            this.status.setForeground(Color.BLACK);
        }
    }

    private WaterHeater_VIEW() {
        initComponents();
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                setVisible(true);
            }
        });
    }

    public static WaterHeater_VIEW getWaterHeaterView() {
        return waterHeaterView;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        status = new javax.swing.JLabel();
        tempreture = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        power = new javax.swing.JLabel();
        switchPowerBtn = new javax.swing.JButton();
        InsertMoney = new javax.swing.JButton();
        moneyEntered = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        Screen = new javax.swing.JTextArea();
        Latte = new javax.swing.JRadioButton();
        Cappuccino = new javax.swing.JRadioButton();
        Espresso = new javax.swing.JRadioButton();
        Mochaccino = new javax.swing.JRadioButton();
        Mocha = new javax.swing.JRadioButton();
        Macchiato = new javax.swing.JRadioButton();
        Sugar = new javax.swing.JSlider();
        jLabel2 = new javax.swing.JLabel();
        Small = new javax.swing.JRadioButton();
        Medium = new javax.swing.JRadioButton();
        Large = new javax.swing.JRadioButton();
        Start = new javax.swing.JButton();
        Cancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        status.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        status.setText("Status");

        tempreture.setEditable(false);
        tempreture.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tempreture.setText("temperature");
        tempreture.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tempretureActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Water Tempreture");

        power.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        power.setText("Power");

        switchPowerBtn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        switchPowerBtn.setText("Switch Power");
        switchPowerBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                switchPowerBtnActionPerformed(evt);
            }
        });

        InsertMoney.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        InsertMoney.setText("Insert Money");
        InsertMoney.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InsertMoneyActionPerformed(evt);
            }
        });

        moneyEntered.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        Screen.setColumns(20);
        Screen.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Screen.setRows(5);
        jScrollPane2.setViewportView(Screen);

        Latte.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Latte.setText("Latte");

        Cappuccino.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Cappuccino.setText("Cappuccino");

        Espresso.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Espresso.setText("Espresso");

        Mochaccino.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Mochaccino.setText("Mochaccino");

        Mocha.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Mocha.setText("Mocha");

        Macchiato.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Macchiato.setText("Macchiato");

        Sugar.setMaximum(5);
        Sugar.setValue(0);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Sugar 0->5");

        Small.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Small.setText("Small");

        Medium.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Medium.setText("Medium");

        Large.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Large.setText("Large");

        Start.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Start.setText("Start");
        Start.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StartActionPerformed(evt);
            }
        });

        Cancel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Cancel.setText("Cancel");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(Start))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap(239, Short.MAX_VALUE)
                                .addComponent(Cancel)))
                        .addGap(70, 70, 70))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(53, 53, 53)
                                .addComponent(jLabel2))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(13, 13, 13)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Medium)
                                    .addComponent(Small)
                                    .addComponent(Large)))
                            .addComponent(Sugar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Mochaccino)
                                    .addComponent(Espresso)
                                    .addComponent(Macchiato)
                                    .addComponent(Cappuccino)
                                    .addComponent(Latte)
                                    .addComponent(Mocha))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel1)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(power)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(switchPowerBtn)
                                        .addComponent(status)
                                        .addComponent(tempreture, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(InsertMoney)
                                .addComponent(moneyEntered, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(61, 61, 61))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(moneyEntered, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(InsertMoney)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 178, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tempreture, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(status)
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(switchPowerBtn)
                    .addComponent(power))
                .addGap(35, 35, 35))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(Start)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Latte)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Cappuccino)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Mocha)
                        .addGap(3, 3, 3)
                        .addComponent(Espresso)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Macchiato)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Mochaccino)
                        .addGap(47, 47, 47)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Sugar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Small)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Medium)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Large)
                        .addGap(52, 52, 52)))
                .addComponent(Cancel)
                .addGap(56, 56, 56))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tempretureActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tempretureActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tempretureActionPerformed

    private void switchPowerBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_switchPowerBtnActionPerformed
        Engine.sendEvent(new Power_EVENT(false));        // TODO add your handling code here:
    }//GEN-LAST:event_switchPowerBtnActionPerformed

    private void InsertMoneyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InsertMoneyActionPerformed
        Money_Dispenser.getMoneyDispenser().swallow(); // TODO add your handling code here:
    }//GEN-LAST:event_InsertMoneyActionPerformed

    private void StartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StartActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_StartActionPerformed

    /**
     * @param args the command line arguments
     */

    public JTextArea getScreen() {
        return Screen;
    }

    /**
     * @param args the command line arguments
     */
    public JTextField getMoneyEntered() {
        return moneyEntered;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Cancel;
    private javax.swing.JRadioButton Cappuccino;
    private javax.swing.JRadioButton Espresso;
    private javax.swing.JButton InsertMoney;
    private javax.swing.JRadioButton Large;
    private javax.swing.JRadioButton Latte;
    private javax.swing.JRadioButton Macchiato;
    private javax.swing.JRadioButton Medium;
    private javax.swing.JRadioButton Mocha;
    private javax.swing.JRadioButton Mochaccino;
    private javax.swing.JTextArea Screen;
    private javax.swing.JRadioButton Small;
    private javax.swing.JButton Start;
    private javax.swing.JSlider Sugar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField moneyEntered;
    private javax.swing.JLabel power;
    private javax.swing.JLabel status;
    private javax.swing.JButton switchPowerBtn;
    private javax.swing.JTextField tempreture;
    // End of variables declaration//GEN-END:variables
}
