/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package system.views;

import Model.Drink;
import Model.Money_Dispenser;
import backend.event.engine.Engine;
import java.awt.Color;
import javax.swing.JButton;
import javax.swing.JRadioButton;
import javax.swing.JSlider;
import javax.swing.JTextArea;
import javax.swing.JTextField;
import system.events.*;

/**
 *
 * @author ragrag
 */
public class WaterHeater_VIEW extends javax.swing.JFrame {

    /**
     * Creates new form WaterHeater_VIEW
     */
    private static final WaterHeater_VIEW waterHeaterView = new WaterHeater_VIEW();

    public void setTemp(String tempreture) {
        this.tempreture.setText(tempreture);
    }

    public void setPower(Boolean power) {
        String pow = power ? "ON" : "OFF";
        this.power.setText(pow);
        if (pow == "ON") {
            this.power.setForeground(Color.GREEN);
        } else if (pow == "OFF") {
            this.power.setForeground(Color.RED);
        }
    }

    public void setStatus(String status) {
        this.status.setText(status);
        if (status == "COOLING") {
            this.status.setForeground(Color.BLUE);
        } else if (status == "HEATING") {
            this.status.setForeground(Color.RED);
        } else {
            this.status.setForeground(Color.BLACK);
        }
    }

    private WaterHeater_VIEW() {
        initComponents();
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                setVisible(true);
            }
        });
    }

    
    public static WaterHeater_VIEW getWaterHeaterView() {
        return waterHeaterView;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        status = new javax.swing.JLabel();
        tempreture = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        power = new javax.swing.JLabel();
        switchPowerBtn = new javax.swing.JButton();
        InsertMoney = new javax.swing.JButton();
        moneyEntered = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        Screen = new javax.swing.JTextArea();
        Sugar = new javax.swing.JSlider();
        jLabel2 = new javax.swing.JLabel();
        Small = new javax.swing.JRadioButton();
        Medium = new javax.swing.JRadioButton();
        Large = new javax.swing.JRadioButton();
        Start = new javax.swing.JButton();
        Cancel = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        Latte = new javax.swing.JButton();
        Americano = new javax.swing.JButton();
        Macchiato = new javax.swing.JButton();
        Cappuccino = new javax.swing.JButton();
        Espresso = new javax.swing.JButton();
        Mocha = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        status.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        status.setText("Status");
        getContentPane().add(status, new org.netbeans.lib.awtextra.AbsoluteConstraints(1190, 340, -1, -1));

        tempreture.setEditable(false);
        tempreture.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tempreture.setText("temperature");
        tempreture.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tempretureActionPerformed(evt);
            }
        });
        getContentPane().add(tempreture, new org.netbeans.lib.awtextra.AbsoluteConstraints(1170, 310, -1, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Water Tempreture");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 280, -1, -1));

        power.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        power.setText("Power");
        getContentPane().add(power, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 390, -1, -1));

        switchPowerBtn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        switchPowerBtn.setText("Switch Power");
        switchPowerBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                switchPowerBtnActionPerformed(evt);
            }
        });
        getContentPane().add(switchPowerBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(1200, 380, -1, -1));

        InsertMoney.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        InsertMoney.setText("Insert Money");
        InsertMoney.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InsertMoneyActionPerformed(evt);
            }
        });
        getContentPane().add(InsertMoney, new org.netbeans.lib.awtextra.AbsoluteConstraints(1150, 230, -1, -1));

        moneyEntered.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        getContentPane().add(moneyEntered, new org.netbeans.lib.awtextra.AbsoluteConstraints(1150, 180, 113, -1));

        Screen.setColumns(20);
        Screen.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Screen.setRows(5);
        jScrollPane2.setViewportView(Screen);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 20, -1, 138));

        Sugar.setMaximum(5);
        Sugar.setValue(0);
        Sugar.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                SugarStateChanged(evt);
            }
        });
        getContentPane().add(Sugar, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 100, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Sugar 0->5");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 50, 110, 20));

        Small.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Small.setText("Small");
        getContentPane().add(Small, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 210, -1, -1));

        Medium.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Medium.setText("Medium");
        getContentPane().add(Medium, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 250, -1, -1));

        Large.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Large.setText("Large");
        getContentPane().add(Large, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 290, -1, -1));

        Start.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Start.setText("Start");
        Start.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StartActionPerformed(evt);
            }
        });
        getContentPane().add(Start, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 50, 110, 50));

        Cancel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Cancel.setText("Cancel");
        getContentPane().add(Cancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 370, 110, 50));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/system/views/coffee_minimal_wallpapers_by_webmozg-d3d9qfb.jpg"))); // NOI18N
        jLabel10.setText("jLabel10");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 0, 800, 430));

        Latte.setIcon(new javax.swing.ImageIcon(getClass().getResource("/system/views/2.jpg"))); // NOI18N
        Latte.setText("Mchiatto");
        Latte.setBorder(javax.swing.BorderFactory.createMatteBorder(5, 5, 5, 5, new java.awt.Color(0, 0, 0)));
        Latte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LatteActionPerformed(evt);
            }
        });
        getContentPane().add(Latte, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 0, 180, 230));

        Americano.setIcon(new javax.swing.ImageIcon(getClass().getResource("/system/views/1.jpg"))); // NOI18N
        Americano.setText("jButton2");
        Americano.setBorder(javax.swing.BorderFactory.createMatteBorder(5, 5, 5, 5, new java.awt.Color(0, 0, 0)));
        Americano.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AmericanoActionPerformed(evt);
            }
        });
        getContentPane().add(Americano, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 210, 220, 220));

        Macchiato.setIcon(new javax.swing.ImageIcon(getClass().getResource("/system/views/3.jpg"))); // NOI18N
        Macchiato.setText("jButton3");
        Macchiato.setBorder(javax.swing.BorderFactory.createMatteBorder(5, 5, 5, 5, new java.awt.Color(0, 0, 0)));
        Macchiato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MacchiatoActionPerformed(evt);
            }
        });
        getContentPane().add(Macchiato, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 0, 180, 230));

        Cappuccino.setIcon(new javax.swing.ImageIcon(getClass().getResource("/system/views/4.jpg"))); // NOI18N
        Cappuccino.setText("jButton4");
        Cappuccino.setBorder(javax.swing.BorderFactory.createMatteBorder(5, 5, 5, 5, new java.awt.Color(0, 0, 0)));
        Cappuccino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CappuccinoActionPerformed(evt);
            }
        });
        getContentPane().add(Cappuccino, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, 200, 220));

        Espresso.setIcon(new javax.swing.ImageIcon(getClass().getResource("/system/views/5.jpg"))); // NOI18N
        Espresso.setText("jButton5");
        Espresso.setBorder(javax.swing.BorderFactory.createMatteBorder(5, 5, 5, 5, new java.awt.Color(0, 0, 0)));
        Espresso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EspressoActionPerformed(evt);
            }
        });
        getContentPane().add(Espresso, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 210, 180, 220));

        Mocha.setIcon(new javax.swing.ImageIcon(getClass().getResource("/system/views/6.jpg"))); // NOI18N
        Mocha.setText("jButton6");
        Mocha.setBorder(javax.swing.BorderFactory.createMatteBorder(5, 5, 5, 5, new java.awt.Color(0, 0, 0)));
        Mocha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MochaActionPerformed(evt);
            }
        });
        getContentPane().add(Mocha, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 190, 210));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tempretureActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tempretureActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tempretureActionPerformed

    private void switchPowerBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_switchPowerBtnActionPerformed
        Engine.sendEvent(new Power_EVENT(false));        // TODO add your handling code here:
    }//GEN-LAST:event_switchPowerBtnActionPerformed

    private void InsertMoneyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InsertMoneyActionPerformed
        Money_Dispenser.getMoneyDispenser().swallow(); // TODO add your handling code here:
    }//GEN-LAST:event_InsertMoneyActionPerformed

    private void StartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StartActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_StartActionPerformed

    private void LatteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LatteActionPerformed
        // TODO add your handling code here:
        
         Engine.sendEvent(new SelectDrink_EVENT(Drink.getDrinks().get(4)));        
    }//GEN-LAST:event_LatteActionPerformed

    private void MochaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MochaActionPerformed
        // TODO add your handling code here:
        Engine.sendEvent(new SelectDrink_EVENT(Drink.getDrinks().get(0)));
    }//GEN-LAST:event_MochaActionPerformed

    private void MacchiatoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MacchiatoActionPerformed
        // TODO add your handling code here:
        Engine.sendEvent(new SelectDrink_EVENT(Drink.getDrinks().get(3)));
    }//GEN-LAST:event_MacchiatoActionPerformed

    private void CappuccinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CappuccinoActionPerformed
        // TODO add your handling code here:
        Engine.sendEvent(new SelectDrink_EVENT(Drink.getDrinks().get(5)));
    }//GEN-LAST:event_CappuccinoActionPerformed

    private void AmericanoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AmericanoActionPerformed
        // TODO add your handling code here:
        Engine.sendEvent(new SelectDrink_EVENT(Drink.getDrinks().get(2)));
    }//GEN-LAST:event_AmericanoActionPerformed

    private void EspressoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EspressoActionPerformed
        // TODO add your handling code here:
        Engine.sendEvent(new SelectDrink_EVENT(Drink.getDrinks().get(1)));
    }//GEN-LAST:event_EspressoActionPerformed

    private void SugarStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_SugarStateChanged
        // TODO add your handling code here:
        Engine.sendEvent(new SelectSuger_EVENT(Sugar.getValue()));
    }//GEN-LAST:event_SugarStateChanged

    /**
     * @param args the command line arguments
     */
    public JTextArea getScreen() {
        return Screen;
    }

    /**
     * @param args the command line arguments
     */
    public JTextField getMoneyEntered() {
        return moneyEntered;
    }
    

//    public void setDrink(Drink drink, boolean state) {
//        switch (drink.getName()) {
//            case "mocha":
//                if (state) {
//                    Mocha.setForeground(Color.GREEN);
//                } else {
//                    Mocha.setForeground(Color.RED);
//                }
//            case "espresso":
//                if (state) {
//                    Espresso.setForeground(Color.GREEN);
//                } else {
//                    Espresso.setForeground(Color.RED);
//                }
//            case "americano":
//                if (state) {
//                    Americano.setForeground(Color.GREEN);
//                } else {
//                    Americano.setForeground(Color.RED);
//                }
//            case "machiatto":
//                if (state) {
//                    Macchiato.setForeground(Color.GREEN);
//                } else {
//                    Macchiato.setForeground(Color.RED);
//                }
//            case "latte":
//                if (state) {
//                    Latte.setForeground(Color.GREEN);
//                } else {
//                    Latte.setForeground(Color.RED);
//                }
//            case "cappuccino":
//                if (state) {
//                    Cappuccino.setForeground(Color.GREEN);
//                } else {
//                    Cappuccino.setForeground(Color.RED);
//                }
//                
//
//        }
//
//    }
//
//    public JRadioButton getAmericano() {
//        return Americano;
//    }
//
//    
//
//    public JRadioButton getCappuccino() {
//        return Cappuccino;
//    }
//
//    public JRadioButton getEspresso() {
//        return Espresso;
//    }
//
//    
//    public JRadioButton getLatte() {
//        return Latte;
//    }
//
//    public JRadioButton getMacchiato() {
//        return Macchiato;
//    }
    
//    public JRadioButton getMocha() {
//        return Mocha;
//    }
    
    public JButton getInsertMoney() {
        return InsertMoney;
    }

    public JRadioButton getLarge() {
        return Large;
    }


    public JRadioButton getMedium() {
        return Medium;
    }

    

    public JRadioButton getSmall() {
        return Small;
    }

    public JButton getStart() {
        return Start;
    }

    public JSlider getSugar() {
        return Sugar;
    }
    
    public JButton getCancel() {
        return Cancel;
    }

    public JButton getAmericano() {
        return Americano;
    }

    public JButton getCappuccino() {
        return Cappuccino;
    }

    public JButton getEspresso() {
        return Espresso;
    }

    public JButton getLatte() {
        return Latte;
    }

    public JButton getMacchiato() {
        return Macchiato;
    }

    public JButton getMocha() {
        return Mocha;
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Americano;
    private javax.swing.JButton Cancel;
    private javax.swing.JButton Cappuccino;
    private javax.swing.JButton Espresso;
    private javax.swing.JButton InsertMoney;
    private javax.swing.JRadioButton Large;
    private javax.swing.JButton Latte;
    private javax.swing.JButton Macchiato;
    private javax.swing.JRadioButton Medium;
    private javax.swing.JButton Mocha;
    private javax.swing.JTextArea Screen;
    private javax.swing.JRadioButton Small;
    private javax.swing.JButton Start;
    private javax.swing.JSlider Sugar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField moneyEntered;
    private javax.swing.JLabel power;
    private javax.swing.JLabel status;
    private javax.swing.JButton switchPowerBtn;
    private javax.swing.JTextField tempreture;
    // End of variables declaration//GEN-END:variables
}
