/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package system.views;

import Model.Money_Dispenser;
import backend.event.engine.Engine;
import java.awt.Color;
import javax.swing.JTextArea;
import javax.swing.JTextField;
import system.events.InsertMoneyEvent;
import system.events.PowerEvent;


/**
 *
 * @author ragrag
 */
public class WaterHeater_VIEW extends javax.swing.JFrame {

    /**
     * Creates new form WaterHeater_VIEW
     */
    private static final WaterHeater_VIEW waterHeaterView = new WaterHeater_VIEW();

    public void setTemp(String tempreture) {
        this.tempreture.setText(tempreture);
    }

    public void setPower(Boolean power) {
        String pow = power ? "ON" : "OFF";
        this.power.setText(pow);
        if (pow == "ON") {
            this.power.setForeground(Color.GREEN);
        } else if (pow == "OFF") {
            this.power.setForeground(Color.RED);
        }
    }

    public void setStatus(String status) {
        this.status.setText(status);
        if (status == "COOLING") {
            this.status.setForeground(Color.BLUE);
        } else if (status == "HEATING") {
            this.status.setForeground(Color.RED);
        } else {
            this.status.setForeground(Color.BLACK);
        }
    }

    private WaterHeater_VIEW() {
        initComponents();
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                setVisible(true);
            }
        });
    }

    public static WaterHeater_VIEW getWaterHeaterView() {
        return waterHeaterView;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        status = new javax.swing.JLabel();
        tempreture = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        power = new javax.swing.JLabel();
        switchPowerBtn = new javax.swing.JButton();
        InsertMoney = new javax.swing.JButton();
        moneyEntered = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        Screen = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        status.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        status.setText("Status");

        tempreture.setEditable(false);
        tempreture.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        tempreture.setText("temp");
        tempreture.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tempretureActionPerformed(evt);
            }
        });

        jLabel1.setText("Tempreture");

        power.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        power.setText("Power");

        switchPowerBtn.setText("Switch Power");
        switchPowerBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                switchPowerBtnActionPerformed(evt);
            }
        });

        InsertMoney.setText("Insert Money");
        InsertMoney.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InsertMoneyActionPerformed(evt);
            }
        });

        moneyEntered.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        Screen.setColumns(20);
        Screen.setFont(new java.awt.Font("Monospaced", 0, 18)); // NOI18N
        Screen.setRows(5);
        jScrollPane2.setViewportView(Screen);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(306, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 19, 19))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(moneyEntered, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(InsertMoney, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(77, 77, 77))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(32, 32, 32))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(tempreture, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(40, 40, 40)
                                    .addComponent(status))))
                        .addGap(64, 64, 64))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(switchPowerBtn)
                        .addGap(18, 18, 18)
                        .addComponent(power)
                        .addGap(50, 50, 50))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(power)
                    .addComponent(switchPowerBtn))
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(tempreture, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(status)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(moneyEntered, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(InsertMoney)
                .addGap(45, 45, 45))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tempretureActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tempretureActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tempretureActionPerformed

    private void switchPowerBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_switchPowerBtnActionPerformed
        Engine.sendEvent(new PowerEvent(false));        // TODO add your handling code here:
    }//GEN-LAST:event_switchPowerBtnActionPerformed

    private void InsertMoneyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InsertMoneyActionPerformed
        Money_Dispenser.getMoneyDispenser().swallow(); // TODO add your handling code here:
    }//GEN-LAST:event_InsertMoneyActionPerformed

    /**
     * @param args the command line arguments
     */

    public JTextArea getScreen() {
        return Screen;
    }

    /**
     * @param args the command line arguments
     */
    public JTextField getMoneyEntered() {
        return moneyEntered;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton InsertMoney;
    private javax.swing.JTextArea Screen;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField moneyEntered;
    private javax.swing.JLabel power;
    private javax.swing.JLabel status;
    private javax.swing.JButton switchPowerBtn;
    private javax.swing.JTextField tempreture;
    // End of variables declaration//GEN-END:variables
}
